name: beet
description: A new Flutter application.

publish_to: 'none'

version: 1.0.2+3

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
#  flutter_cupertino_localizations: ^1.0.1
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  provider: ^6.1.2
  # share: ^2.0.4
  js: ^0.7.1
  cloud_firestore: ^5.6.2
  cloud_functions: ^5.3.1
  firebase_core: ^3.10.1
  firebase_core_web: ^2.19.0
  # firebase_app_check: ^0.2.1
  firebase_storage: ^12.4.1
  firebase_auth: ^5.4.1
  firebase_dynamic_links: ^6.1.1
  firebase_analytics: ^11.4.1
  image_picker: ^1.1.2
  image_cropper: ^9.0.0
  image_gallery_saver_plus: ^3.0.5
  cached_network_image: ^3.4.1
  table_calendar: ^3.1.3
  nholiday_jp: ^1.0.2
  animated_text_kit: ^4.2.3
  webview_flutter: ^4.10.0
  bubble_tab_indicator: ^0.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/app_icon.png
    - images/user_profile.png
    - images/group_profile.png
  fonts:
    - family: MPLUS1p
      fonts:
        - asset: fonts/MPLUS1p-Black.ttf
        - asset: fonts/MPLUS1p-Bold.ttf
        - asset: fonts/MPLUS1p-ExtraBold.ttf
        - asset: fonts/MPLUS1p-Light.ttf
        - asset: fonts/MPLUS1p-Medium.ttf
        - asset: fonts/MPLUS1p-Regular.ttf
        - asset: fonts/MPLUS1p-Thin.ttf