name: beet
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1
  cupertino_icons: ^0.1.3
  intl: ^0.17.0
  provider: ^4.3.3
  share: ^0.6.5+4
  cloud_firestore: ^1.0.1
  cloud_functions: ^1.0.0
  firebase_core: ^1.0.3
  firebase_storage: ^8.0.3
  firebase_auth: ^1.1.0
  firebase_dynamic_links: ^0.8.0
  firebase_analytics: ^7.0.1
  image_picker: ^0.7.4
  image_cropper: ^1.4.0
  image_gallery_saver: ^1.6.9
  cached_network_image: ^3.0.0
  table_calendar: ^2.3.3
  nholiday_jp: ^1.0.1
  animated_text_kit: ^4.1.0
  webview_flutter: ^1.0.7
  bubble_tab_indicator: ^0.1.6
  implicitly_animated_reorderable_list: ^0.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/app_icon.png
    - images/user_profile.png
    - images/group_profile.png
  fonts:
    - family: MPLUS1p
      fonts:
        - asset: fonts/MPLUS1p-Black.ttf
        - asset: fonts/MPLUS1p-Bold.ttf
        - asset: fonts/MPLUS1p-ExtraBold.ttf
        - asset: fonts/MPLUS1p-Light.ttf
        - asset: fonts/MPLUS1p-Medium.ttf
        - asset: fonts/MPLUS1p-Regular.ttf
        - asset: fonts/MPLUS1p-Thin.ttf